fixtures:
    forge_modules:
        stdlib: "puppetlabs/stdlib"
        api: "tsuru/api"
        router: "tsuru/router"
        docker: "tsuru/docker"
        gandalf: "tsuru/gandalf"
        apt:
            repo: "puppetlabs/apt"
            ref: 1.6.0
        base:
            repo: "tsuru/base"
            ref: 0.0.4
        firewall:
            repo: "puppetlabs/firewall"
            ref: 1.1.3
        redis:
            repo: "fsalum/redis"
            ref: 1.0.2
        python:
            repo: "stankevich/python"
            ref: 1.9.0
    symlinks:
        tsuruio: "#{source_dir}/modules/tsuruio"
